
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 24 23:53:21 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 8;
  public static final int Operador_relacional = 18;
  public static final int For = 11;
  public static final int Suma = 13;
  public static final int Numero = 31;
  public static final int Operador_booleano = 21;
  public static final int Operador_incremento = 20;
  public static final int Operador_atribucion = 19;
  public static final int ERROR = 32;
  public static final int Identificador = 30;
  public static final int Comillas = 3;
  public static final int Int = 5;
  public static final int Parentesis_cierre = 23;
  public static final int Corchete_apertura = 26;
  public static final int Corchete_cierre = 27;
  public static final int Tipo_dato = 4;
  public static final int Main = 28;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int Operador_logico = 17;
  public static final int Division = 16;
  public static final int Parentesis_apertura = 22;
  public static final int Resta = 14;
  public static final int If = 7;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Llave_apertura = 24;
  public static final int Do = 9;
  public static final int Llave_cierre = 25;
  public static final int Igual = 12;
  public static final int While = 10;
  public static final int Multiplicacion = 15;
  public static final int Punto_coma = 29;
}

